spring:
  application:
    name: recipe-generator

  ai:
    openai:
      api-key:
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4.1
#          temperature: 0.1

logging:
  level:
    org.springframework.web.client: DEBUG
    org.springframework.ai: DEBUG

server:
    port: 8088


